=== mcgivrer/Games/dtd/themes.dtd
<!ELEMENT theme (shortname, name, description, author, (author_long)?, version, date, encoding)>
<!ELEMENT shortname (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT author_long (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT encoding (#PCDATA)>

=== mcgivrer/Games/themes/default/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "//WebContext//DTD Themes 1.0/EN" "../../dtd/themes.dtd">
<theme>
	<shortname>default</shortname>
	<name>Default</name>
	<description>A default theme for the template rendering framework</description>
	<author>Frederic Delorme(frederic.delorme@gmail.com)</author>
	<version>1.0</version>
	<date>2010/08/12</date>
	<encoding>UTF-8</encoding>
</theme>

=== mcgivrer/Games/themes/html5/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "//WebContext//DTD Themes 1.0/EN" "../../dtd/themes.dtd">
<theme>
	<shortname>html5</shortname>
	<name>HTML5</name>
	<description>A HTML 5 oriented design for the template rendering framework</description>
	<author>F. Delorme</author>
	<author_long>Frederic Delorme(frederic.delorme@gmail.com)</author_long>
	<version>1.0</version>
	<date>2010/08/12</date>
	<encoding>UTF-8</encoding>
</theme>
